#!/usr/bin/env sh

#
# Copyright 2015 the original author or authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then to run this script, type that shell name before the whole
#       command line, like:
#
#           ksh Gradle startScripts/gradle
#
#       Busybox and similar reduced shells will NOT work, because this script
#       requires all of these POSIX shell features:
#         * functions;
#         * expansions "$var", "${var}", "${var:-default}", "${1+"$@"}";
#         * compound commands having a testable exit status, especially "case";
#         * various built-in commands including "command", "set", and "trap".
#
#   Important for patching:
#
#   (1) This script targets any POSIX shell, so avoid extensions provided
#       by Bash, Ksh, etc; in particular arrays are avoided.
#
#   (2) The inline ergo solution uses "return" to return on success rather
#       than using a POSIX shell construct that will work with any shell.
#
#   In particular, shellcheck defines by default for sh files the set of
#   rules which behaves as equivalent to passing the shellcheck --shell=sh
#   option.
#
##############################################################################

set -eu

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" && pwd )
APP_HOME=$( cd -- "$( dirname -- "$(readlink -f "$0")" )" && pwd )

# Add a user-defined property if it is specified
if [ -z "${1}" ]; then
    echo >&2 "Error: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    echo >&2
    echo >&2 "Please set the JAVA_HOME variable in your environment to match the"
    echo >&2 "location of your Java installation."
    exit 1
fi

exec "$SCRIPT_DIR/gradle" "$@"
